apiVersion: v1
kind: Service
metadata: 
   name: petclinceapp-svc
   labels: 
       app: petclinicapp
       type: petclinceapp-svc

spec: 
    type: LoadBalancer
    ports:
        - port: 80
          targetPort: 9000
    selector: 
      app: petclinicapp
      type: petclinicapp-dev
   